server:
  port: 3000

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: community-service
          uri: http://community-service:3002
          predicates:
            - Path=/api/community/**
          filters:
            - StripPrefix=2
            
        - id: event-service
          uri: http://event-service:3003
          predicates:
            - Path=/api/events/**
          filters:
            - StripPrefix=2
            
        - id: user-service
          uri: http://user-service:3001
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.partizip: DEBUG
