server:
  port: 3003

spring:
  application:
    name: event-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.partizip: DEBUG
